name: Check out, Build and Upload Artifacts
description: Common action to check out the repository, build the addon, and upload artifacts to Dropbox and Cloudflare R2.

inputs:
  addon_version:
    required: true
    description: "Version of the addon to upload, e.g., v1.0.0"
  addon_platform:
    required: true
    description: "Platform of the addon, e.g., MacArm64, MacX64, LinuxX64, WinX64"
  target_extension:
    required: false
    description: "Target extension to build, e.g., 'so' for shared object files, 'pyd' for Windows DLLs"
  python_version:
    required: false
    description: "Python version to use"
  requirements_file:
    required: false
    description: "Path to the requirements file, default is 'requirements.txt'"
    default: 'requirements.txt'

  # repo
  my_repo:
    required: true

  # secrets (显式传入)
  ssh_key:
    required: true

  dropbox_refresh_token:
    required: true
  dropbox_app_key:
    required: true
  dropbox_app_secret:
    required: true

  r2_account_id:
    required: true
  r2_access_key_id:
    required: true
  r2_secret_access_key:
    required: true
  r2_bucket:
    required: true

runs:

  using: "composite"

  steps:
    - uses: git9527/clean-up-action@v3

    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.my_repo }}
        ssh-key: ${{ inputs.ssh_key }}
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ inputs.requirements_file }}

    - name: Build binaries
      shell: bash
      run: cd scripts && sh github-build.sh ${{ inputs.target_extension }} ${{ inputs.addon_platform }}

    - name: Upload to Dropbox
      uses: git9527/deploy-to-dropbox@v22
      with:
        DROPBOX_REFRESH_TOKEN: ${{ inputs.dropbox_refresh_token }}
        DROPBOX_APP_KEY: ${{ inputs.dropbox_app_key }}
        DROPBOX_APP_SECRET: ${{ inputs.dropbox_app_secret }}
        DROPBOX_DESTINATION_PATH_PREFIX: /addon/${{ inputs.addon_version }}/
        GLOB_PATTERN: ${{ inputs.addon_platform }}*.*

    - name: Upload to CF R2
      uses: git9527/r2-upload-action@v6
      with:
        r2-account-id: ${{ inputs.r2_account_id }}
        r2-access-key-id: ${{ inputs.r2_access_key_id }}
        r2-secret-access-key: ${{ inputs.r2_secret_access_key }}
        r2-bucket: ${{ inputs.r2_bucket }}
        glob-pattern: ${{ inputs.addon_platform }}*.*
        destination-dir: addon/${{ inputs.addon_version }}