name: Build All Packages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target remote branch name'
        default: 'master'


jobs:

  Build_For_Win64_38:

    runs-on: windows-2022
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "pyd" "WindowsAMD6438"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Win64_39:

    runs-on: windows-2022
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "pyd" "WindowsAMD6439"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Win32_38:

    runs-on: windows-2022
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'
          cache: 'pip'
          architecture: 'x86'
      - name: Install dependencies
        run: pip install -r requirements-win38.txt
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "pyd" "WindowsX8638"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Ubuntu_38:

    runs-on: ubuntu-22.04
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip==23
          pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "so" "LinuxX6438"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Ubuntu_39:

    runs-on: ubuntu-22.04
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip==23
          pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "so" "LinuxX6439"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Ubuntu_311:

    runs-on: ubuntu-22.04
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip==23
          pip install -r requirements.txt
          
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build.sh "so" "LinuxX64311"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}

  Build_For_Mac_38:

    runs-on: macos-13
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build-mac.sh "so" "DarwinX6438"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}


  Build_For_Mac_39:

    runs-on: macos-13
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests
        
      - name: Build binaries
        run: cd scripts && sh common-github-build-mac.sh "so" "DarwinX6439"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}
        
  Build_For_Mac_Arm:

    runs-on: macos-14
    timeout-minutes: 7

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        run: |
          brew reinstall python@3.9
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          python3.9 -V
        
      - name: Install dependencies
        run: pip3.9 install -r requirements-arm.txt

      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests

      - name: Build binaries
        run: cd scripts && sh common-github-build-arm.sh "so" "DarwinArm6439"

      - name: Upload to Dropbox
        uses: git9527/deploy-to-dropbox@v22
        with:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ env.ADDON_VERSION }}/
          GLOB_PATTERN: ${{ env.ADDON_PLATFORM }}*.*

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Upload to CF R2
        run: |
          aws s3 sync ${{ env.ADDON_PLATFORM }} s3://${{ vars.R2_BUCKET }}/${{ env.ADDON_VERSION }}/${{ env.ADDON_PLATFORM }} --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.R2_REGION }}
  
