name: Build Arm

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch name'
        required: true


jobs:

  Build_For_Arm:

    runs-on: macos-14
    timeout-minutes: 5

    steps:
      - uses: git9527/clean-up-action@v1
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build binaries
        run: sh common-github-build-arm.sh "so" "DarwinArm6439"

      - name: Set up Aliyun OSS
        uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

      - name: Sync file to oss
        run: ossutil cp output-binary/${{ env.ADDON_PLATFORM }}.zip oss://${{ vars.OSS_KEY_BUCKET }}/ultimate-template/${{ env.ADDON_VERSION }}/ --force
