name: Build All Packages V3

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Manual input version"
        default: "latest"

  repository_dispatch:
    types: [ lib-repo-updated-v3 ]

jobs:

  Prepare_Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - id: extract-version
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          echo "version=$VERSION" >> $GITHUB_ENV

  Build_For_Mac_Intel_38:

    needs: Prepare_Version
    runs-on: macos-13
    timeout-minutes: 8

    steps:
      - name: Action Checkout
        uses: actions/checkout@v4

      - name: Common Build Process
        uses: ./.github/actions/upload-files
        with:
          addon_version: ${{ env.ADDON_VERSION }}
          addon_platform: "DarwinX6438"
          target_extension: "so"
          python_version: "3.8"
          requirements_file: "requirements.txt"

  Build_For_Mac_Intel_39:

    needs: Prepare_Version
    runs-on: macos-13
    timeout-minutes: 8

    steps:
      - name: Action Checkout
        uses: actions/checkout@v4

      - name: Common Build Process
        uses: ./.github/actions/upload-files
        with:
          addon_version: ${{ env.ADDON_VERSION }}
          addon_platform: "DarwinX6439"
          target_extension: "so"
          python_version: "3.9"
          requirements_file: "requirements.txt"

  Build_For_Mac_Intel_313:

    needs: Prepare_Version
    runs-on: macos-13
    timeout-minutes: 8

    steps:
      - name: Action Checkout
        uses: actions/checkout@v4

      - name: Common Build Process
        uses: ./.github/actions/upload-files
        with:
          addon_version: ${{ env.ADDON_VERSION }}
          addon_platform: "DarwinX64313"
          target_extension: "so"
          python_version: "3.13"
          requirements_file: "requirements.txt"
