name: Build Arm

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch name'
        default: 'master'


jobs:

  Build_For_Mac_Arm:

    runs-on: macos-14
    timeout-minutes: 10

    steps:
      - uses: git9527/clean-up-action@v3
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MY_REPO }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python
        run: |
          brew reinstall python@3.9
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          python3.9 -V
        
      - name: Install dependencies
        run: pip3.9 install -r requirements-arm.txt

      - name: Run tests
        env:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
        run: pytest tests

      - name: Build binaries
        run: cd scripts && sh common-github-build-arm.sh "so" "DarwinArm6439"

      - name: Upload to Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
          --header "Dropbox-API-Arg: {\"path\": \"/${{ env.ADDON_VERSION }}/{{ $env.ADDON_PLATFORM }}.zip\", \"mode\": \"add\", \"autorename\": true, \"mute\": false}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @${{ env.ADDON_PLATFORM }}.zip
          echo "Uploading hash file"
          curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
          --header "Dropbox-API-Arg: {\"path\": \"/${{ env.ADDON_VERSION }}/{{ $env.ADDON_PLATFORM }}-hash.txt\", \"mode\": \"add\", \"autorename\": true, \"mute\": false}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @${{ env.ADDON_PLATFORM }}-hash.txt

